force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <label>Compensation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <inlineHelpText>Select your job category from the list or select other to enter another one</inlineHelpText>
    <label>Job Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Semi-Senior</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MVD WTC 2</fullName>
            </value>
            <value>
                <fullName>MVD WTC 1</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCompensationDataFactory.cls
public abstract class TestCompensationDataFactory {
	//Compensation creation
    public static List<Compensation__c> createCompensations(Integer numberOfCompensations) {
        List<Compensation__c> compensations = new List<Compensation__c>();
        for (Integer i = 0 ; i < numberOfCompensations ; i++) {
            String location = rLocation();
            Compensation__c comp = new Compensation__c(RecordTypeId = rRecordType(),
        											  	Name = 'Test Comp' + i,
                                                       	Contact__c = '0033h000001shV0AAI',
                                                        Location__c = location,
                                                        Office__c = rOffice(location),
                                                        Job_Category__c = 'Junior',
                                                        Description__c = 'Desc Comp' + i );
            compensations.add(comp);
        }
      return compensations;
            
    }
    
    public static String rRecordType(){
        String recordType = '';
        Integer randomNumber = Integer.valueof((Math.random() * 2));
        switch on randomNumber {
            when 0 {
                recordType = '0123h000000H5sIAAS';
            }
            when 1 {
                recordType = '0123h000000H5smAAC';
            }
            when 2{
                recordType = '0123h000000H5sNAAS';
            }
        }  
 		system.debug('Record Type Generated'+ recordType);
        return recordType;
    }
    
    public static String rLocation(){
        String location = '';
        Integer randomNumber = Integer.valueof((Math.random() * 2));
        switch on randomNumber {
            when 0 {
                location = 'India';
            }
            when 1 {
                location = 'Uruguay';
            }
            when 2{
                location = 'US';
            }
        }
        
        return location;
    }
    
    public static String rOffice(String sLocation){
        String office = '';
        switch on sLocation {
            when 'India' {
                office = 'Chennai';
            }
            when 'Uruguay' {
                office = 'MVD WTC 2';
            }
            when 'US'{
                office = 'Michigan';
            }
        }
        return office;
    }

}