force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <label>Compensation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked means it is ready for management approval.</description>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubmitCompensations_Batch.cls
global class SubmitCompensations_Batch implements Database.Batchable<sObject>{
 
    global Database.QueryLocator start(Database.BatchableContext BC){
     	String query = 'SELECT Name, Submitted__c, CreatedDate FROM Compensation__c';	
        return Database.getQueryLocator(query);
     }
     
     global void execute(Database.BatchableContext BC, List<Compensation__c> l_comp){
         for(Compensation__c comp : l_comp){
             Integer daysDifference  = (system.today()).daysBetween(Date.valueOf(comp.CreatedDate));
             if(comp.Submitted__c == False && daysDifference > 2){
                 comp.Submitted__c = True;
             }
             update comp;
         }
     }
     
     global void finish(Database.BatchableContext BC){
     }
     
}